"""Stage registry: dependency order + metadata. Extended as stages are implemented."""
from . import (
    s0_env,
    s1_validate,
    s2_normalize,
    s3_blocking,
    s3b_audit,
    s3g_blocking,
    s3h_blocking,
    s4_features,
    s5_model,
    s6_rerank,
    s6b_llm,
    s7_decision,
    s8_outputs,
    s9_validate,
    s10_package,
    s_eda,
    s_splits,
)

STAGES = {
    "s0_env": {"run": s0_env.run, "desc": "hardware/environment detection gate (S0)"},
    "validate_data": {"run": s1_validate.run, "desc": "S1 data validation gate over all 7 TSVs"},
    "eda": {"run": s_eda.run, "desc": "train-only noise statistics (reports/eda.md)"},
    "splits": {"run": s_splits.run, "desc": "grouped 90/10 split by S1 entity"},
    "normalize": {"run": s2_normalize.run, "desc": "S2 normalization of all 6 source files (parquet)"},
    "blocking": {"run": s3_blocking.run, "desc": "S3 multi-strategy blocking -> candidate pairs (train+test)"},
    "blocking_audit": {"run": s3b_audit.run, "desc": "S3b blocking recall audit on val (gates S4)"},
    "blocking_g": {"run": s3g_blocking.run, "desc": "S3-G trigram top-K for ALL S1 rows (recall rescue)"},
    "blocking_h": {"run": s3h_blocking.run, "desc": "S3-H address-token top-K for ALL S1 rows (generic-name rescue)"},
    "features": {"run": s4_features.run, "desc": "S4 pair feature engineering (vectorized, sharded)"},
    "model": {"run": s5_model.run, "desc": "S5 LightGBM pair classifier + val F0.5 sweep"},
    "rerank": {"run": s6_rerank.run, "desc": "S6 bge-reranker difficult-band scoring (guarded)"},
    "llm": {"run": s6b_llm.run, "desc": "S6b guarded Qwen2.5-7B adjudication of ambiguous band"},
    "decision": {"run": s7_decision.run, "desc": "S7 calibration + decision engine (F0.5 thresholds)"},
    "outputs": {"run": s8_outputs.run, "desc": "S8 write matching_results.tsv + candidate_pairs.tsv"},
    "validate": {"run": s9_validate.run, "desc": "S9 official validator PASS gate (+ optional --check-ids)"},
    "package": {"run": s10_package.run, "desc": "S10 fill docs + build submission zip"},
}
